#!/bin/bash
# JankyBorders Configuration - Catppuccin Latte Theme
# Location: ~/.config/borders/bordersrc

options=(
    style=round
    width=5.0
    hidpi=on
    active_color=0xffff1493      # Catppuccin Latte Blue
    inactive_color=0x25ff1493    # Catppuccin Latte Surface1
)

borders "${options[@]}"
